[server]
port = 3000

[database]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"
database = "postgres"
schema = "public"

[logger]
level = "info"

[logger.format]
level = true
file = true
line_number = true
target = false
thread_ids = false
thread_names = false
ansi = true
